name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: docker-build-and-publish
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: .
        image-name: devopstask
        tags: maaaaaarkova/devopstask latest
    
