name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: github-actions-godolint
      uses: zabio3/github-actions-godolint@v0.1.8
      with:
        github_token: ${{secrets.github_token}}
    
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: maaaaaarkova/devopstask:latest

